keon/algorithms

- README.md
- math/pythagoras.py
> added pythagoras.py to maths

- tree.md
Github rendering looks a lot better this way
> Wrap in <pre> tags with by making the whole file a code block

- README.md
> Broken Link Readme

- bit/add_without_operator.py
Added new file: add_without_operator.py
The file uses bitwise operators to add two numbers instead of
the '+' operator.
> Add two numbers without using '+' operator

- dp/combination_sum.py
- string/make_sentence.py
- Rewrite make_sentence.py to python from C++
- Rewrite combination_sum.py to python from Java
issue: #15
> Rewrite make_sentence.py and combination_sum.py to python

- backtrack/word_search.py
Added the solution to Word Search II on LeetCode under the backtrack directory
> add algorithm to backtrack

- map/longest_common_subsequence.py
- map/valid_sudoku.py
Use the snake_case instead of camelCase (for pythonic code)
> Convert the camelCase to snake_case

- string/reverse_words.py
Going by the current logic:
Input: I am keon kim and I like pizza
Output: apizz like I and kim keon am I
The first word 'apizz' is NOT correctly reversed to 'pizza'.
The reason being- when 'start' is '0', the 'if' block is not evaluated. 
After fix:
Input: I am keon kim and I like pizza
Output: pizza like I and kim keon am I
> Fixed checks in 'if' conditions

- sort/merge_sort.py
> Small mistake in sort/merge_sort.py array merge

- sort/merge_sort.py
Return arr at the end of merge function in sort/merge_sort.py file.
Issue: #31 
Correction to: #45
> Small mistake in sort/merge sort.py array merge

- matrix/search_in_sorted_matrix.py
Search a key in a row wise and column wise sorted matrix, in linear time.
> Added code to search in a row wise and column wise sorted matrix.

- math/prime_test.py
Modifying the code to improve efficiency
> #58 | Correct the logic of Prime testing function in math/test_primt.py

- array/garage.py
> cleanup garage.py

- bit/add_without_operator.py
1. Fixed comment, as the code adds only positive integers successfully.
2. Fixed pep8 changes
> Fixes in comments and code-style

- array/plus_one.py
Simplify the overly complicated math in the present solutions
-added bonus: Lesser LOC.
> Add an easier solution to plus_one.py

- array/plus_one.py
i think use method insert to unshift the num to the list was better
> use method insert() rather than new a variable

- README.md
- matrix/count_paths.py
Starting from the top left cell, one can move right or bottom to reach bottom right cell of the matrix.
The number of unique paths are calculated.
> Added code to find the number of unique paths in a matrix

- README.md
- sort/counting_sort.py
(i) Moved the file to 'sort/' folder
(ii) Added new entry to README.md
> Changed location of counting_sort.py

- bit/count_ones.py
As mentioned in the comments, the code would work only for unsigned integers.
If a negative integer is provided as input, then the code runs into an
infinite loop. To avoid this, we are checking if the input is negative.
If yes, then return control before loop is entered.
> Check if the input is negative

- README.md
- graph/cycle_detection.py
Adding an implementation and a respective entry in the README.
> Adding a cycle detection algorithm for graphs.

- README.md
- dp/knapsack.py
Adding the implementation and a respective README entry.
> Adding an implementation for the knapsack problem.

- README.md
- sort/bubble_sort.py
- sort/comb_sort.py
https://en.wikipedia.org/wiki/Comb_sort
> Implemented Comb Sort

- array/garage.py
I fixed the incorrect algorithm for the garage problem with keeping the time complexity O(n^2). It now passes the test given in issue #61.
> Algorithm for garage problem fixed

- README.md
- graph/markov_chain.py
Hope it's okay. I imagine it might not be simple enough, or it might be that the generator is too much -- curious to know whether it's okay. I think markov chains would be a good addition to this collection!
> Added a Markov Chain implementation

- README.md
- graph/satisfiability.py
I implemented an algorithm for the 2-SAT problem.
It's a classic algorithm that constructs an implication graph, finds its strongly connected components, and assigns true/false values to them in topological order.
> 2-SAT algorithm

- array/rotate_array.py
Added naive solution, for better understanding of various approaches to solve this problem.
> Rotate array one by one

- string/reverse_string.py
Add a simple and pythonic function of reversing a string.
> Add different implementation of reverse_string.py

- array/circular_counter.py
If we store in memory len(list) we can run this algorithm too much faster.
> Optimized circular_counter code, faster

- README.md
- README_CN.md
- backtrack/factor_combinations.py
> Revert " update array_sum_combinations and readme"

- README.md
- graph/tarjan.py
Hi @keon. maybe adding the Tarjan's strongly connected components finder algorithm would be a good addition.
As the name says, Tarjan's algorithm finds these type of components in a graph. These components are subgraphs where every vertex can be reached from any other vertex in the same component.
In social networks, this could indicate a close group of friends where everyone knows everyone. Another algorithm for this same task is the Kosaraju's algorithm.
> Add Tarjan's strongly connected component finder

- array/garage.py
Also fixed the bug where the function `garage()` reflects the changes in the original initial array passed to it by creating a copy of it inside the function.
Also added documentation.
> garage.py now also prints the sequence of steps.

- graph/checkDiGraphStronglyConnected.py
- graph/pathBetweenTwoVerticesInDiGraph.py
> added some graph algo

- dp/matrix_chain_order.py
Adding Dynamic programming Implementation of Matrix Chain order
> MatrixChainOrder

- graph/Transitive_Closure_DFS.py
- graph/graph.py
Transitive Closure of a Graph using DFS
Graph.py update with addedge function -> tested with other graph scripts in this repo.
> Added transitive closure and graph.py update

- calculator/math_parser.py
I improved the code:  
- more efficient  in the ```evaluate(...)```  
- added a error management in the ```parser(...)``` and in the UI.  
And I added a simple user interface (command-line)
> calculator: improved the code and added a simple user interface

- matrix/bomb_enemy.py
I maked the code more efficient. Put in some comments and added a testsuite (unittest) for the project.
> Changed bomb_enemy.py in directory matrix

- stack/stack.py
I added a test suite for the ```stack.py```. Using unittest
> Test stack.py

- linkedlist/add_two_numbers.py
I added two new functions:
```python
def convert_to_list(number : int) -> "Node":
def convert_to_str(l : "Node") -> str:
```
And I added a testsuite for the linked list and the full functionality of the project (uses unittest).
> linkedlist: added a testsuite and two functions for converting

- stack/valid_parenthesis.py
I added a test suite to the file ```valid_parenthesis.py```.
> valid_parenthesis.py: added a testsuite

- maths/prime_test.py
I removed a unnecessary 'else'. And I added a test suite (unittest).
> Changed prime test.py

- array/circular_counter.py
- array/flatten.py
- array/longest_non_repeat.py
- array/merge_intervals.py
Format, fix flake8 errors, refactor.
Would be cool when there would be template for examples,
something like this:
```python
"""
Algorithm description
"""
def my_algorithm():
return "My new algorithm!"
if __name__ == "__main__":
import unittest
class TestMyAlgorithm(unittest.TestCase):
""" Do the tests here. """
pass
```
> UPDATE add tests, refactor, fix flake8 errors

- queues/max_sliding_window.py
- queues/queue.py
- stack/simplify_path.py
- stack/stack.py
- stack/valid_parenthesis.py
Also made some refactoring in stacks and queues.
> Fixed Queues implementations and add tests.

- README.md
> add Christian as a maintainer

- backtrack/array_sum_combinations.py
- bit/add_without_operator.py
- dp/combination_sum.py
- dp/max_product_subarray.py
- graph/satisfiability.py
- linkedlist/copy_random_pointer.py
- matrix/count_paths.py
- strings/breaking_bad.py
- strings/make_sentence.py
- tree/pretty_print.py
Get us closer to compatibility with Python 3 without losing any existing Python 2 compatibility...
* __print()__ is a function in Python 3
* missing imports
* missing indentation
* define __raw_input()__, __reduce()__, etc.
* misc PEP8 cleanup
> Fix Python 3 related issues

- backtrack/anagram.py
* I improved the function anagram (removed the while loop):
```python
def anagram(s1,s2):
```  
* I renamed one of the functions ```all_perms```  
```python
def all_perms_iter(elements):
```  
* And I added a test suite (unittest)
> Improved and test suite for anagram.py

- array/flatten.py
- also added 2 more test cases.
> bug fix #173

- map/hashtable.py
I kept the tests and roll back the origin code for the hashtable. 
* I extended the test suite. All test ran successful
> pulled the origin code and extended the test suite

- CONTRIBUTING.md
The writing in the issues section was confusing, rewrite for clarity.
> Improve issues section of CONTRIBUTING.md

- array/garage.py
- array/longest_non_repeat.py
- array/merge_intervals.py
- array/missing_ranges.py
- array/move_zeros_to_end.py
- array/plus_one.py
- array/rotate_array.py
- array/summary_ranges.py
- array/three_sum.py
- array/two_sum.py
> completed tests for array module

- bfs/word_ladder.py
- fixed the function for corner cases.
- wrote tests for those cases.
- fixes #182
> add tests and fix #182 issue

- README.md
- linkedlist/is_sort.py
- linkedlist/remove_range.py
Hello,
I add some problem related to Linkedlist. Could you help me review them? Thanks
> Add some problem to Linkedlist

- search/first_occurance.py
- search/last_occurance.py
I simplefied in two more files the calculation of the middle.
> simplefied the calculation of the mid.

- README.md
- stack/is_consecutive.py
- stack/is_sorted.py
- stack/remove_min.py
- stack/stutter.py
- stack/switch_pairs.py
Hello,
I add some problem into stack. I know what you (@goswami-rahul ) mean about `unittest`. I add them into my file instead of using print. Thanks
> Add some problem to stack

- dfs/all_factors.py
I added a test suite and change the division operator from / to //. In addition I added some doc string documentations.
> Added a test suite and change the division operator from / to //.

- sort/merge_sort.py
I changed the division operator from ```/``` to ```//```. Now we can run the code successful.
> fixed merge_sort.py

- sort/insertion_sort.py
I fixed the ```insertion_sort.py```. I changed ```xrange``` to ```range```. Now we can ran the file.
> fixed insertion_sort.py.

- sort/selection_sort.py
I fixed the ```selection_sort.py```. I changed ```xrange``` to ```range```. No we can ran the algorithm
> fixed selection_sort.py

- dfs/sudoku_solver.py
* I added a class-framework.  
* Added a simple test case with a ```main()``` method.
* Renamed the methods according to PEP.  
* Added a test for availability of ```xrange```  
* Added a ```__str__``` method. 
I will add a test suite (unittest)
> Changed sudoku solver

- sort/bubble_sort.py
- sort/comb_sort.py
- sort/counting_sort.py
- sort/heap_sort.py
- sort/insertion_sort.py
- sort/merge_sort.py
- sort/quick_sort.py
- sort/selection_sort.py
PR to add `unittest` to sort. It has some issues in `merge_sort`, `insertion_sort`, and `selection_sort`. I am going to rewrite these sort
> Add unittest to sort

- tree/bst/bst.py
Hi, I implement the bst tree. `insert`, and `search` works now. But I am not sure why `size` method does not work: 
The error:  `AttributeError: 'NoneType' object has no attribute 'size' `
@goswami-rahul  @christianbender Could you help me?
> Implement bst tree

- README.md
- tree/bst/bst.py
- tree/bst/count_left_node.py
- tree/bst/depth_sum.py
- tree/bst/height.py
- tree/bst/num_empty.py
PR to add some problem to bst along with test case. A commit fix typo in `bst.py`
> Add some problem to bst

- sort/bubble_sort.py
- sort/comb_sort.py
- sort/counting_sort.py
- sort/heap_sort.py
- sort/insertion_sort.py
- sort/merge_sort.py
- sort/quick_sort.py
- sort/selection_sort.py
- sort/test_sort.py
PR for separating test case for sort
> Separate test case for sort

- bit/add_bitwise_operator.py
- bit/count_ones.py
- bit/find_missing_number.py
- bit/power_of_two.py
- bit/reverse_bits.py
- bit/single_number.py
- bit/single_number2.py
- bit/subsets.py
- bit/test_bit.py
PR for separating test for bit
> Separate test for bit

- maths/rsa.py
- maths/test_maths.py
**Fix for #226**  
* I changed the encryption level on 26 bits.  
* I wrote a new test which runs 100 times.  (successful).
* With a high encryption level the encryption is save.  
* disadvantage: The process takes an extremely long time.  
* I comment out this test, because it takes a while.
> Fixed test_maths.py

- README.md
- README_CN.md
- map/separate_chaining_hashtable.py
I just added a separate chaining hash table implementation here. Have a nice day!
> Add SeparateChainingHashTable implementation

- strings/is_palindrome.py
So, I was going through our repo and found that we only have one variation of is_palindrome. So I decided to add a couple more. BTW I opened a PR request from my repo's master but @goswami-rahul  told me to do it from a separate branch so I have closed that request. Plus, I also narrowed the commits to just a single one.  
Also, the algorithms can be found on geeksforgeeks.com. I thought it'd be nice to have different versions for the readers.
> Add is_palindrome variations

- strings/is_palindrome.py
fix the minor syntax error (indentation) in `strings/is_palindrome.py`
> fix the error in is_palindrome

- tests/test_maths.py
* I moved the tests of the module ```maths``` in the directory ```tests```.
> I moved the tests for maths in the directory tests

- heap/binary_heap.py
- heap/skyline.py
- stack/is_consecutive.py
- stack/is_sorted.py
- stack/remove_min.py
- stack/simplify_path.py
- stack/stack.py
- stack/stutter.py
- stack/switch_pairs.py
- stack/valid_parenthesis.py
- tests/test_heap.py
- tests/test_stack.py
PR to add test_heap and test_stack to tests.
> Add heap and stack to test

- graph/graph.py
- graph/tarjan.py
- tests/test_graph.py
Hi @danghai and @keon, I've fixed the possible errors reported at #240 by sorting each strongly connected component. The sort is done by the Node's name, that's why I added comparison methods on Node class. I also moved the graph tests file to the new correct directory.
It should be working now!
> Fix tarjan tests

- strings/add_binary.py
- strings/breaking_bad.py
- strings/decode_string.py
- strings/domain_extractor.py
- strings/encode_decode.py
- strings/group_anagrams.py
- strings/int_to_roman.py
- strings/is_palindrome.py
- strings/license_number.py
- strings/make_sentence.py
- strings/merge_string_checker.py
- strings/rabin_karp.py
- strings/reverse_string.py
- strings/reverse_vowel.py
- strings/strip_url_params.py
- strings/validate_coordinates.py
- strings/word_squares.py
- tests/test_strings.py
* I wrote tests for the module ```strings``` and put the file ```test_strings.py``` in the directory ```tests```.  
***important:*** The file ```strip_url_params.py``` is buggy. Because one times the tests run successful and a other times it fails. I comment out the test for this file. See #256   
@SaadBenn Can you look in it? The project with the bug is from you. More information #256
> Tests for the module strings

- tree/avl/avl.py
Implementation of Avl tree
Notes:
Test cases will be added in another branch
Recommend any other methods I need to put in
> Avl tree implementation (#198)

- .coveragerc
- .gitignore
- .travis.yml
- README.md
- maths/prime_check.py
- tests/test_maths.py
PR to add coverall to algorithms. 
test coverage is measurement to find how much of your codebase is covered by testing with the ultimate goal of making project 100% covered by tests. It does this by running all of your tests (unit tests) and keeping track of what lines of the project source code is executed and not executed while running your tests.
@christianbender : It has one issue in `prime_test`. Could you help me review it? I am not sure why it is missing n in parameter. btw, I fix a minor in your `test_math`. 
@keon , @goswami-rahul , @SaadBenn . What do you think? 
Look at this site for my repo about coverall:
https://coveralls.io/github/danghai/algorithms
> Add coverall to algorithms

- queues/max_sliding_window.py
- queues/queue.py
- queues/reconstruct_queue.py
- tests/test_queues.py
PR to add test_queue to tests.
Resolve #258
> Add test_queue to tests

- .gitignore
- .travis.yml
- README.md
- setup.py
PR to make python packaging locally. 
I write the `setup.py` file. It successful install after command `sudo pip install .`. Unfortunately, I cannot import the `algorithms` package. You can test by creating the file `test.py` with content:
```python
import algorithms
def main():
my_list = [1, 8, 3, 5, 6]
my_list = insertion_sort(my_list)
print(my_list)
```
Error:
```
File "test.py", line 1, in <module>
import algorithms
ImportError: No module named 'algorithms'
```
Am I missing something? What do you think @keon , @goswami-rahul , @christianbender , @SaadBenn
> Python packaging locally

- README_GE.md
* I added a german readme ```README_GE.md```  
* I also changed the main readme ```README.md```  
* Added a link to the german readme.
> added a german readme and changed the main-readme

- strings/is_rotated.py
- tests/test_strings.py
I added an algorithm to strings. This checks if a string is a rotated version of another string and returns a bool. A few tests were added to test_strings.py as well.
> Add is_rotated.py

- algorithms/sort/__init__.py
- algorithms/sort/bucket_sort.py
- algorithms/sort/shell_sort.py
- tests/test_sort.py
It seems like there are no bucket sort and shell sort in the sort file, so I added them. Updated test_sort.py as well - added bucket and shell sort in the test.
> Created bucket_sort.py & shell_sort.py and Updated test_sort.py

- README_CN.md
- README_GE.md
- README_JP.md
It seems like https://github.com/keon/algorithms/pull/299 corrected the link to Josephus problems in English README file, so I corrected other languages as well!
> Corrected link to Arrays/Josephus Problems

- README.md
- README_CN.md
- README_GE.md
- README_JP.md
It seems like Korean README file is created, so I added link to Korean file from other README files - English, Chinese, German and Japanese.
> Added link to Korean README file in other README files

- README.md
- README_CN.md
- README_GE.md
- README_JP.md
- README_KR.md
- algorithms/maths/__init__.py
- algorithms/maths/combination.py
- tests/test_maths.py
I created combination.py that calculates nCr. Also added test cases as well.
> Created combination.py in maths

- README.md
- README_CN.md
- README_GE.md
- README_JP.md
- README_KR.md
- algorithms/sort/__init__.py
- algorithms/sort/radix_sort.py
- tests/test_sort.py
It seems like there are no radix_sort in the sort file, so I added it.
> Created radix_sort.py in algorithms/sort

- README_CN.md
- README_GE.md
- README_JP.md
- README_KR.md
It seems like there is no link to linear search that I just created in README files(Chinese, German, Korean and Japanese), so I added them :)
> Added link to linear search in all README files

- README.md
- README_CN.md
- README_GE.md
- README_JP.md
- README_KR.md
- algorithms/maths/__init__.py
- algorithms/maths/factorial.py
- tests/test_maths.py
I also modified a TestCombination comment
> Created factorial.py in algorithms/maths

- README.md
- README_CN.md
- README_GE.md
- README_JP.md
- README_KR.md
- algorithms/sort/__init__.py
- algorithms/sort/bogo_sort.py
- tests/test_sort.py
Although bogo_sorting is not useful for sorting, it can be used in training through comparison with the algorithms that actually used. It is also used as an example of logic type programming.
> Created bogo_sort.py in algorithms/sort

- README_CN.md
- README_JP.md
- README_KR.md
There were some README files that do not have these information in top of the page (English and German already had them), so I added them in Korean, Japanese and Chinese files.
> Added link to OS Helpers, Build Status, and Coverage Status in README files.

- README.md
- setup.py
Thanks to Nic(@nryoung), we are live in PyPI!
He also agreed to join us as a maintainer, so please welcome!
now you can install the package with simple `pip install algorithms`.
> add to python package index

- README.md
- README_CN.md
- README_GE.md
- README_JP.md
- README_KR.md
- algorithms/sort/__init__.py
- algorithms/sort/bitonic_sort.py
- tests/test_sort.py
Create bitonic_sort.py in /algorithms/sort/ and update test_sort, __init__ and all README files
If anything wrong, please comment me
Thank you,
> Create bitonic_sort.py in /algorithms/sort/ and update test_sort, __init__ and all README files

- algorithms/sort/bubble_sort.py
I added simulation feature in bubble sort by adding  a new parameter 'simulation'. For example, if the input array is [4,2,3,4,6,1] and you set simulation = True when calling the function, you will see:
[4,2,3,4,6,1]
[2,4,3,4,6,1]
[2,3,4,4,6,1]
[2,3,4,1,4,6]
[2,3,1,4,4,6]
[2,1,3,4,4,6]
[1,2,3,4,4,6]
> Added simulation in bubble sort

- README_CN.md
- README_GE.md
- README_JP.md
- README_KR.md
> logo update in all READMEs

- .travis.yml
- MANIFEST.in
- requirements.txt
- tests/test_backtrack.py
- tests/test_queues.py
- tox.ini
> WIP: Fix some issues in Travis and add more python env 

- README.md
- README_CN.md
- README_GE.md
- README_JP.md
- README_KR.md
- algorithms/sort/__init__.py
- algorithms/sort/pancake_sort.py
- tests/test_sort.py
- [ X ] **If creating a new file :**
- [ X ] added links to it in the README files ?
- [ X ] included tests with it ?
- [ X ] added description (overview of algorithm, time and space compleixty, and possible edge case) in docstrings ?
> Created pancake_sort.py in algorithms/sorts

- README.md
- README_CN.md
- README_GE.md
- README_JP.md
- README_KR.md
- algorithms/graph/__init__.py
- algorithms/graph/check_bipartite.py
- tests/test_graph.py
I implemented a function that checks whether the graph is a bipartite graph or not. Also added three different test cases in tests/test_graph.py.
> Created check_bipartite.py in algorithms/graph + test cases

- README.md
- algorithms/unix/__init__.py
- algorithms/unix/path/full_path.py
- algorithms/unix/path/join_with_slash.py
- algorithms/unix/path/split.py
- tests/test_unix.py
> PR to make some path problems

- MANIFEST.in
> remove `tests/*` from MANIFEST.in

- algorithms/sort/radix_sort.py
For issue #315, I made a change for simulating radix_sort
Thanks
> simulation code for radix_sort

- algorithms/sort/bogo_sort.py
An issue about #315 :)
I deleted my forked repo. So I made a new PR. I also accepted a review
> simulation code for bogo_sort, Re-PR

- README.md
- algorithms/strings/__init__.py
- algorithms/strings/judge_circle.py
- algorithms/strings/strong_password.py
- algorithms/strings/unique_morse.py
- tests/test_strings.py
> Add some String algorithm

- algorithms/maths/combination.py
- tests/test_maths.py
#357 I try to improve combination.py
> improvement combination.py using memoization

- README.md
- README_GE.md
- README_JP.md
- README_KR.md
> Correction in README files

- .travis.yml
- README.md
- README_CN.md
- README_GE.md
- README_JP.md
- README_KR.md
- algorithms/maths/__init__.py
- algorithms/maths/extended_gcd.py
- algorithms/maths/factorial.py
- algorithms/maths/modular_exponential.py
- algorithms/maths/nth_digit.py
- algorithms/maths/prime_check.py
- algorithms/maths/primes_sieve_of_eratosthenes.py
- algorithms/maths/rsa.py
- algorithms/maths/sqrt_precision_factor.py
- requirements.txt
- test_requirements.txt
- tests/test_maths.py
- removed requirements for testing from `requirements.txt` since tests are no longer included in package. There is no dependencies for this repo as of now (apart from tests).
- removed `prime_check2`. Too similar to `prime_check`
- other refactoring.
> added exponential and some refactors to maths/

- README.md
- algorithms/strings/__init__.py
- algorithms/strings/repeat_string.py
- algorithms/unix/__init__.py
- algorithms/unix/path/simplify_path.py
- tests/test_strings.py
- tests/test_unix.py
> Add some solution 

- algorithms/strings/strip_url_params.py
- tests/test_strings.py
> Revert "Fixes #256 change strip_url_params3 to stop flaky unit test failures"

- README.md
- README_CN.md
- README_GE.md
- README_JP.md
- README_KR.md
- README_PTBR.md
> Corrected language title

- algorithms/strings/__init__.py
- algorithms/strings/text_justification.py
- tests/test_strings.py
> add text_justification and test text_justification

- algorithms/backtrack/generate_parenthesis.py
- tests/test_backtrack.py
rename generate_parenthesis to generate_parenthesis_v1, add generate_parenthesis_v2 and test.
> generate_parenthesis

- algorithms/arrays/longest_non_repeat.py
- tests/test_array.py
> Fix longest_non_repeat by sliding windown method

- CONTRIBUTING.md
Included language inviting contributors to improve documentation.
> edited Contributing.md to add 'doc_xxx' option

- algorithms/search/linear_search.py
In `linear_search.py`, a new variable is created for the length of the array, but only used once. So I figured, why not just get rid of the variable instead?
> No need to create a variable for length in linear_search.py

- algorithms/sort/bubble_sort.py
- as after each step of 'outer-loop', one number reaches to its right position. Thus inner loop does not need to run for 'n' times in every cycle of 'outer-loop'.
- [ x] **if done some changes :**
- [ x] wrote short description in the PR explaining what the changes do ?
- [ x] Fixes #[issue number] if related to any issue
> Optimize bubbe sort

- README.md
- algorithms/maths/__init__.py
- algorithms/maths/euler_totient.py
- tests/test_maths.py
> add Euler's Totient function

- algorithms/arrays/plus_one.py
- algorithms/linkedlist/__init__.py
- algorithms/linkedlist/copy_random_pointer.py
- tests/test_linkedlist.py
> Fix array plus one v3

- algorithms/dp/__init__.py
- algorithms/dp/edit_distance.py
- tests/test_dp.py
> Add edit distance DP problem

- README.md
- algorithms/maths/hailstone.py
- tests/test_maths.py
> Add hailstone algorithm

- algorithms/matrix/rotate_image.py
> fix function definition

- algorithms/heap/binary_heap.py
> edit swap one liner

- algorithms/graph/minimum_spanning_tree.py
> Fix invoking function name

- algorithms/calculator/math_parser.py
> fix calculator infinite loop

- README.md
- algorithms/heap/__init__.py
- algorithms/heap/k_closest_points.py
- tests/test_heap.py
> Add k closest points to origin

- tests/test_heap.py
without the change in line #5, this will not work.
> fix: test_heap.py

- .gitignore
- .vscode/settings.json
> Remove the .vscode folder and add it to .gitignore

- algorithms/tree/bst/is_bst.py
- [ x ] wrote short description in the PR explaining what the changes do ?
1. fix errors: the loop will nerver be excuted
2. remove redundant statement
> fix a error in is_bst.py

- tests/test_heap.py
- tests/test_tree.py
- Add testcases for inorder tree traversal
- Fix k_closest_points test cases
> Add test cases for inorder traversal

- README.md
- algorithms/compression/huffman_coding.py
- tests/test_compression.py
> Add huffman coding (encode and decode file), add tests for huffman coding.

- README.md
- algorithms/compression/huffman_coding.py
- algorithms/tree/b_tree.py
- tests/test_compression.py
- tests/test_tree.py
> Add b-tree

- PULL_REQUEST_TEMPLATE.md
- tox.ini
> Fix a typo in the pull request template

- .travis.yml
- tox.ini
> Travis CI: Drop the EOL Python 3.4 and add 3.7 

- .travis.yml
- algorithms/arrays/move_zeros.py
- algorithms/tree/red_black_tree/red_black_tree.py
Highlight that identity is not the same thing as equality in Python.  Use ==/!= to compare str, bytes, and int literals.
> Travis CI: Add more flake8 tests

- algorithms/sort/radix_sort.py
- [X ] **If creating a new file :**
- [X ] added links to it in the README files ?
if max_number is a multiple of 10, like [1,2,3,4,5,6,7,8,9,10], then result will be [10,1,2,3,4,5,6,7,8,9]
> fix error if max_number is a multiple of 10

- README.md
- algorithms/compression/rle_compression.py
- tests/test_compression.py
> Added RLE algorithm

- README.md
- algorithms/maths/__init__.py
- algorithms/maths/cosine_similarity.py
- tests/test_maths.py
I added the function in `algorithms/maths/cosine_similarity.py` that calculates the cosine similarity between two python lists.
> Add cosine similarity calculation.

- README.md
- algorithms/matrix/cholesky_matrix_decomposition.py
- tests/test_matrix.py
> Add cholesky matrix decomposition

- algorithms/bfs/maze_search.py
Reformated the code to be better readable. 
Corrected time and space complexity. 
Replaced `list` with `collections.deque` for faster pops and appends.
> Reformat maze_search

- algorithms/graph/find_path.py
> Remove debug print

- algorithms/arrays/flatten.py
Updated `collections` import in `algorithms/arrays/flatten.py`.
> Fix collections.iterable warning

- algorithms/dp/longest_common_subsequence.py
> Added Longest Common Subsequence Algorithm under DP section

- README.md
- algorithms/compression/elias.py
- tests/test_compression.py
Elias gamma and delta data compression algorithms to expand the category.
> Added elias gamma and delta data compression codings

- README.md
- algorithms/graph/dijkstra.py
- tests/test_graph.py
> Added dijkstra test and missing link from documentation

- algorithms/arrays/limit.py
> Reformat arrays/limit.py

- algorithms/dp/regex_matching.py
> Corrected function calls in regex_matching.py (fixed 8 tests)

- README.md
- algorithms/tree/segment_tree/iterative_segment_tree.py
- tests/test_iterative_segment_tree.py
Added iterative version of the segment tree data structure with tests.
> Add iterative segment tree

- algorithms/dp/longest_increasing.py
- tests/test_dp.py
> Add dp longest increasing optimized

- algorithms/search/jump_search.py
Resolves a small typo in a comment in algorithms/search/jump_search.py
> Fix simple typo: taget -> target

- algorithms/maths/gcd.py
- tests/test_maths.py
> Add gcd bit

- algorithms/dp/coin_change.py
> optimized coin_change (space complexity quadratic -> linear)

- algorithms/dp/knapsack.py
> simple optimizations for knapsack code

- README.md
- algorithms/graph/__init__.py
- algorithms/graph/bellman_ford.py
- algorithms/sort/merge_sort.py
- tests/test_graph.py
> Add bellman-ford algorithm

- README.md
- algorithms/automata/DFA.py
- algorithms/automata/__init__.py
- algorithms/sort/merge_sort.py
- tests/test_automata.py
- [ x] **If creating a new file :**
- [x ] added links to it in the README files ?
> Add dfa.py

- algorithms/bfs/__init__.py
- algorithms/bfs/count_islands.py
- tests/test_bfs.py
> Add bfs count islands

- algorithms/dfs/__init__.py
- algorithms/dfs/maze_search.py
- tests/test_dfs.py
> Add dfs maze search

- algorithms/automata/dfa.py
- algorithms/graph/tarjan.py
This addresses recommendations from LGTM. <https://lgtm.com/rules/7900090/>
> Fix problems with testing equality to None.

- README.md
- algorithms/matrix/matrix_inversion.py
- tests/test_matrix.py
> Add matrix inversion

- algorithms/dp/fib.py
Added the basic description of Fibonacci Numbers and the main aim of the functions.
> Added Fibonacci Description

- algorithms/strings/is_palindrome.py
Removed seemingly unnecessary code. Open to any corrections
> Optimized string is_palindrome main function

- README.md
issue: https://github.com/keon/algorithms/issues/713
tested working fine ^^
> fixing link for connected component in readme

- algorithms/tree/red_black_tree/red_black_tree.py
> fixing delete_fixup() in red_black_tree

- README.md
- algorithms/maths/__init__.py
- algorithms/maths/krishnamurthy_number.py
- tests/test_maths.py
I have added the Krishnamurthy Number checker algorithm. This is a common algorithm that is pretty famous here in India especially from a beginner's perspective. 
Talking of Krishnamurthy number,  it's a number whose sum total of the factorials of each digit is equal to the number itself.
**hacktoberfest-accepted**
> Add Krishnamurty Number to Math algorithms 

- README.md
- algorithms/maths/__init__.py
- algorithms/maths/magic_number.py
- tests/test_maths.py
NOTE - in "tests/test_maths.py" I only added tests for the algorithm I added. My IDE formatted the file.
_P.S. Please add **"hacktoberfest-accepted"** to this PR._ <3
> Add Magic Number to maths algorithms

- README.md
- algorithms/dp/__init__.py
- algorithms/dp/k_factor.py
- tests/test_dp.py
I have implemented an algorithm to solve a dp problem named "K-factor" 
Problem statement: The K factor of a string is defined as the number of times ‘abba’ appears as a substring.
Given two numbers N and k,​ find the number of strings of length N with ‘K factor’ = k.
> Adding k_factor.py in dp folder in add_K_FactorofStrings branch

- algorithms/heap/binary_heap.py
This is my first pull request.
> Corrected spelling anf grammar errors in docstring for heap.

- algorithms/heap/binary_heap.py
- algorithms/strings/rotate.py
Fixed spelling and grammar errors as well as method signature.
> Updated binary_heap

- algorithms/heap/binary_heap.py
- algorithms/linkedlist/linkedlist.py
- algorithms/maths/base_conversion.py
- algorithms/matrix/matrix_exponentiation.py
- algorithms/matrix/matrix_inversion.py
- algorithms/strings/rotate.py
- algorithms/tree/max_height.py
- algorithms/tree/min_height.py
Fixed invalid references and some more spelling errors.
> Fixed some invalid references and more spelling errors.

- README.md
- algorithms/map/longest_palindromic_subsequence.py
- tests/test_map.py
This is my first GitHub contribution. I hope my pull request is added. 
Fixed Issue - #746
> LPS Algorithm is Added Fixed Issues #746

- algorithms/arrays/limit.py
> Increase performance of Function

- tests/test_strings.py
Adds a missing import for the test of rotate_alt
> Bugfix: Add missing import for rotate_alt test

- README.md
- algorithms/sort/__init__.py
- algorithms/sort/exchange_sort.py
- tests/test_sort.py
I have added exchange sort algorithm
> Added exchange sort

- .github/workflows/python-app.yml
Invoke pytest as a python module rather than a standalone executable.
> Update pytest command.

- algorithms/arrays/limit.py
Its bugging me that CI workflow is failing because of a test for this function. This bug fix should bring green ticks back again. ;)
> Bug fix: Add None checks for the boundary values.

- tests/test_strings.py
I saw that there were no unit tests for the algorithm so I decided to write some.
> Added test cases for the fizzbuzz algorithm.

- algorithms/maths/diffie_hellman_key_exchange.py
> Missing `f` prefix on f-strings fix

- algorithms/tree/red_black_tree/red_black_tree.py
"==" or "!=" can raise exception (maximum recursion depth), because they compares all fields of all nodes. "is" checks that objects have the same pointer in the memory.
> "delete_fixup" optimization

- CONTRIBUTING.md
- algorithms/matrix/matrix_exponentiation.py
> Fixed typos

- algorithms/search/search_range.py
- tests/test_search.py
fix: #804
- Fix search_range
- Add test case
```
nums = [5,7,7,7,7,8,8,8,8,10]
target = 7
search_range(nums , target)
```
```
output : [1, 4] 
```
> Fix search_range and add test

- algorithms/maths/fft.py
- tests/test_maths.py
> add FFT and tests

- algorithms/arrays/longest_non_repeat.py
Added window sliding approach to find longest non repeating sub string.
> Add window sliding approach

- algorithms/graph/strongly_connected_components_kosaraju.py
- tests/test_graph.py
> Add Kosaraju algorithm

- tests/test_array.py
test case file test_array.py is missing a comma at line 12
> Update test_array.py (missing comma at line 12)

- algorithms/sort/bead_sort.py
This PR adds the Bead Sort algorithm to solve issue #920.
> Added Bead Sort Algorithm #920
