math/sqrt_precision_factor.py

Also removed java code in docstring.

implemented square root with precision

---

queue/moving_average.py

* Imported `__future__.division` (to ensure true division is used whether using Python 2 or 3)
* Imported `collections.deque` (previously missing)
* Used the `maxlen` argument for `deque` (instead of checking `len(self.queue) > self.size`)
* `sum` shouldn't be used as a variable name (since it shadows the builtin function name)
* Added `if __name__ == '__main__'` (to ensure tests are not run if the file is imported)
* Fixed the tests so they wouldn't raise `SyntaxError`'s

'moving_average' fixes

---

README.md

I've made the all links between title and source code for #24 
1. Able to see the source code for all algorithms on README right away
2. Separate the `implementation` section and `design` section for readability
3. Hide some non-algorithm source files such as `__init__.py` and cache related files
You can squash the two commits with message as this PR title

Make links between algorithm title and python source code

---

map/hashtable.py

Previously: `HashTable ` was:
1. Not fully implemented
2. `put` method was of `O(N)` complexity due to this `hashval not in keys`
3. `put` method crashed with `NameError`
Main issues addressed:
1. Implementing all the API from the docs
2. Implementing `put` with O(1) complexity
3. Added unit tests
4. Added `ResizableHashTable` subclass that grows exponentially in space
5. PEP8 formatting
Thanks

Hashtable fixes

---

math/primes_sieve_of_eratosthenes.py

Complexity and space reduced to a half.

Sieve of Eratosthenes optimization.

---

stack/stack.py

I fixed the method:  
```python
def peek(self):
```
from the class ArrayStack. Now the method returns the current top element of the stack.

fixed peek() method of the ArrayStack

---

.travis.yml

[Flake8](http://flake8.pycqa.org) tests can help to find Python syntax errors, undefined names, and other code quality issues.  [Travis CI](https://travis-ci.org) is a framework for running flake8 and other tests which is free for open source projects like this one.  The owner of the this repo would need to go to https://travis-ci.org/profile and flip the repository switch __on__ to enable free automated flake8 testing of each pull request.

Add Travis CI to do automated testing

---

README.md
strings/strip_url_params.py

The function removes duplicate query strings based off of an optional argument passed to the function. If the argument is empty then just remove any duplicates otherwise remove duplicates as well as the corresponding duplicates of the passed argument.

Add strip_url_params function.

---

linkedlist/is_cyclic.py
linkedlist/is_sorted.py
linkedlist/merge_two_list.py
linkedlist/remove_range.py
linkedlist/reverse.py
linkedlist/swap_in_pairs.py
linkedlist/test_linkedlist.py

PR for separating test for linkedlist.
Fix #162 
I write a function convert from `Node` to `list` for testing. Now, we can use `assertEqual` in unittest. There are still some test case that need to be added. 
I am going to add some problem relating to them too. It is first draft, please review them.
@keon , @goswami-rahul

Separate test for linkedlist, enhance and add some problem

---

queues/priority_queue.py

I know this is not an efficient way to do it but our repo was missing a priority queue implementation and I thought I might just just give it a try.

Add priority heap implementation using lists.

---

algorithms/queues/priority_queue.py
tests/test_queues.py

`collections.deque` didn't had `insert` method in Python 3.4, so replaced it with `list`. Time Complexity is unchanged, and refactored code a little bit.
`__init__` now also takes list of items to initialize queue.

refactor PriorityQueue and tests

---

README.md
README_CN.md
README_GE.md
README_JP.md
README_KR.md
algorithms/tree/traversal/__init__.py
algorithms/tree/traversal/inorder.py
algorithms/tree/traversal/postorder.py
algorithms/tree/traversal/preorder.py
tests/test_tree.py

I created two tree traversal algorithms - preorder & postorder. Each of them has two functions recursive and non-recursive. I added sample test in the same file, which is same as inorder traversal.

Created Preorder & Postorder traversals in tree

---

algorithms/strings/strip_url_params.py
tests/test_strings.py

Use OrderedDict to preserve query string key order. This should prevent `?a=1&b=2` returning          
`?b=2&a=1` sometimes and failing the test even though it's semantically correct.
- [x ] **if done some changes :**
- [x ] wrote short description in the PR explaining what the changes do ?
- [ x] Fixes #[issue number] if related to any issue

Fixes #256 change strip_url_params3 to stop flaky unit test failures

---

algorithms/sort/radix_sort.py

Use `position` as a loop variable instead of `is_done` to fix the bug that isn't to be find easily.
#395

fix sort/radix_sort (#395)

---

algorithms/search/search_rotate.py

There is an `if not array` check in `search_rotate.py`, even when this is not necessary because the code would not enter the while loop anyway if the size of the array is 0.

Initial check at beginning of `search_rotate.py` is useless

---

README.md
algorithms/matrix/sum_sub_squares.py
tests/test_matrix.py

(Put an X inside the [ ] to denote check mark [X].)
Added a function to calculate the sums of sub squares in a given matrix.

Add sum of sub squares of a given nxn matrix

---

tests/test_strings.py

Add two more tests to `bracket(words, symbols)` function in `strings/breaking_bad.py`. Adding these tests results in 100% branch coverage for the function. 
- Test 1: Test to match symbols that do not exist in the word list. This should return the words without any changes made to them.
- Test 2: Try to match two duplicate symbols. It should only encapsulate the match once ([i]), not twice ([[i]]).

Add two more breaking bad tests

---

algorithms/graph/__init__.py

I noticed the prism_minimum_spanning wasn't imported in the __init__.py so I include it and the tests run normally again.  See below
Before:
After:

fix import prism_minimum_spanning import

---

tests/test_sort.py

Added helper function to allow for easier testing of future algorithms

Updated sorting tests to make tests more readable.

---

README.md
algorithms/strings/__init__.py
algorithms/strings/check_pangram.py
tests/test_strings.py

add check pangram to strings folder + add test for it

add check pangram

---

README.md
algorithms/streaming/__init__.py
algorithms/streaming/misra_greis.py
algorithms/streaming/misra_gries.py
tests/test_streaming.py

Added the Misra-Gries streaming algorihtm and the corresponding tests.

Add misra-gries streaming algorithm

---

algorithms/search/interpolation_search.py

Hi there. I have found an issue when searching for a negative integer:
After fixing: 
In addition, there is an issue when the author using the built-in ***in*** operator that will use the Timsort algorithm to search for an element in the given range. This being said, we are using a built-in searching algorithm for another searching algorithm. Thus, I have changed the condition at this line: 
https://github.com/keon/algorithms/blob/8f6e5f0aa54fe82c00d677cda2f8bef345f001ad/algorithms/search/interpolation_search.py#L37 
More details about this built-in operator can be found at: 
- https://docs.python.org/dev/whatsnew/3.2.html#optimizations
- https://docs.python.org/3/library/stdtypes.html#ranges
- https://docs.python.org/3/library/stdtypes.html#common-sequence-operations 
Besides the bug …

Fix failed test with negative search key and refactor code

---

algorithms/strings/rotate.py

The way it was, you couldn't pass in a rotation higher than the length of the string doubled without getting a blank string in return. This way allows you to pass in any positive integer and get a result.
Also,
The last line of the description said that it took 2 strings and returned a boolean. This is not correct. The first line of the comment is correct.

fix_rotate.py

---

algorithms/map/__init__.py
algorithms/map/longest_palindromic_subsequence.py
tests/test_map.py

this could be an implementation of lps. it can return the logestSubStr as well.you can remove the '#' in the last line to do it.

this could be an implementation of lps.

---

README.md

`fenwick tree` was in the list of links twice, and the first instance was a broken link. This removes the duplicate & broken link.

Fix broken & duplicate link in wiki

---

algorithms/sort/heap_sort.py

There is a small typo in algorithms/sort/heap_sort.py.
Should read `occurred` rather than `occured`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, occured -> occurred

---

algorithms/sort/merge_sort.py

It looks like there is no need to create a copy, we can replace the new elements inplace by mutating the contents of array.

modified the return from both main and helper.

---

README.md
algorithms/arrays/__init__.py
algorithms/arrays/remove_duplicates.py
tests/test_array.py

This algorithm simply removes any duplicates from an array.

Add remove duplicates
